version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: task_app
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
    networks:
      - task_network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/task_management?serverVersion=15&charset=utf8

  webserver:
    image: nginx:alpine
    container_name: task_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task_network

  database:
    image: postgres:15-alpine
    container_name: task_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_management
    networks:
      - task_network

networks:
  task_network:
    driver: bridge

volumes:
  postgres_data: